### ISSUE TITLE
Error loggin in

### ISSUE THREAD

**Issue by Xeroner** [dragonbanshee/node-steam-parentbot#10]
`Error logging in: TypeError: Cannot read property 'send' of undefined`

Any idea?

**Comment by mert574** [comment]
Please share your code

**Comment by Xeroner** [comment]
Now it's logging in i don't know why
But i have another issue, after first login etc now i can't login

http://scr.hu/9li8/xch9j

code :
` var util = require('util');
var ParentBot = require('steam-parentbot'); //change to 'steam-parentbot' if not running from examples directory
var Steam = ParentBot.Steam; //instance of the Steam object

var ChildBot = function () {
    ChildBot.super_.apply(this, arguments);
}

util.inherits(ChildBot, ParentBot);

var Bot = new ChildBot('xxxx', 'xxxx');

Bot.connect(); `

**Comment by mert574** [comment]
EResult: 5 means wrong password. That's why you cannot login.

If you are sure that your password is correct, then you probably restarted bot too often so steam have blocked you. Wait around ~10mins and try again, it should work as expected.

**Comment by Xeroner** [comment]
That was i think :))) Thanks

**Comment by Xeroner** [comment]
ahhh it's happend after second connect... Bulshit

**Comment by Xeroner** [comment]
http://scr.hu/9li8/fouej

**Comment by mert574** [comment]
EResult: 85 means, your account is 2FA enabled but you are trying to login without 2FA. In other words, you are not passing the sharedSecret

Do you pass the sharedSecret to childbot?

```
var util = require('util');
var ParentBot = require('steam-parentbot'); //change to 'steam-parentbot' if not running from examples directory
var Steam = ParentBot.Steam; //instance of the Steam object

var ChildBot = function () {
ChildBot.super_.apply(this, arguments);
}

util.inherits(ChildBot, ParentBot);

var Bot = new ChildBot('xxxx', 'xxxx' {
    sharedSecret: '[shared secret here]'  // <------------
});
Bot.connect();
```

**Comment by Xeroner** [comment]
Thanks man, i'm now connected :)))
Is there maby some array where are info about logged?

I mean something like :

console.log(isLogged); // True or False

**Comment by kjsmita6** [comment]
The 2fa info is written to a file once it's enabled,  as lono as you did it through the bot. It's called username.2fa_info.

**Comment by Xeroner** [comment]
I mean something like :

console.log(isLogged); // True or False

**Comment by mert574** [comment]
You want something like logOnResponse event i think. @dragonbanshee can help you about how you can edit already defined events

**Comment by Xeroner** [comment]
LogOnResponse returns me back info but it's only one time, i need to check is logged in every 5 seconds

**Comment by mert574** [comment]
Not sure if it's the right way to do it but you can do it like:
define a variable
set it to true with LogOnResponse
set it to false with loggedOff

**Comment by kjsmita6** [comment]
There's a node-steam property called loggedOn that determines whether you are logged in or not. 

You can use something like this to see if you're logged in:

```
setInterval (function () {
    console.log(Bot.steamClient.loggedOn);
}, 5000);
```

This will log true if logged on and false if logged off every five seconds.

**Comment by CodeLuca** [comment]
where do you get the shared secret from?
