### ISSUE TITLE
Handling sended offers :)

### ISSUE THREAD

**Issue by Xeroner** [dragonbanshee/node-steam-parentbot#13]
Hi there, witch function take care of ofers sended from bot :) 
How to accept etc

**Comment by andrewda** [comment]
`Bot.offers` should be all you need access offers. Read the documentation.

**Comment by kjsmita6** [comment]
As @andrewda said, `Bot.offers` is an instance of [Alex7Kom/node-steam-tradeoffers](https://github.com/Alex7Kom/node-steam-tradeoffers) and everything you need for trade offers can be found there.
