### ISSUE TITLE
What is an identity secret?

### ISSUE THREAD

**Issue by CodeLuca** [dragonbanshee/node-steam-parentbot#15]
```
identitySecret: 'XXXXXXXXX/XXXXXXXXXXXXXXX/X=', //identity secret, needed to automatically confirm trade offers, must be used with confirmationInterval
```

**Comment by andrewda** [comment]
That is the secret key which allows your bot to accept/send trade offers

**Comment by CodeLuca** [comment]
But how do you find it?

Sent from myMail for iOS

Friday, 18 March 2016, 19:20 +0000 from notifications@github.com  notifications@github.com:

**Comment by mert574** [comment]
http://www.lmgtfy.com/?q=where+to+find+steam+identity+secret

**Comment by CodeLuca** [comment]
@infam0us that doesn't help much considering the second result is this github repo

**Comment by CodeLuca** [comment]
@infam0us or im blind lol :3

**Comment by mert574** [comment]
@CodeLuca Let me even click that for you :P it actually depends on where did you actually activated your 2FA. Where did you activated it?

**Comment by CodeLuca** [comment]
@infam0us im using mobile auth?

**Comment by mert574** [comment]
@CodeLuca with your phone, right?
For IOS: http://forums.backpack.tf/index.php?/topic/45995-guide-how-to-get-your-shared-secret-from-ios-device-steam-mobile/
For Android: http://forums.backpack.tf/index.php?/topic/46354-guide-how-to-find-the-steam-identity-secret-on-an-android-phone/

**Comment by CodeLuca** [comment]
thx

**Comment by mert574** [comment]
np m8

**Comment by kjsmita6** [comment]
The identity secret is found on the generated file when you activate 2fa via parentbot.

**Comment by CodeLuca** [comment]
@dragonbanshee inside the sentry or log?

**Comment by CodeLuca** [comment]
inside the sentry or log?

**Comment by mert574** [comment]
@CodeLuca inside sentry

**Comment by CodeLuca** [comment]
@infam0us how does one read a sentry file?

**Comment by mert574** [comment]
@CodeLuca I'm really sorry. It's not sentry. it is in [steam-username].2fa_info . If you don't have one, you didn't activated via parentbot.

**Comment by CodeLuca** [comment]
could you direct me how to activate it?

**Comment by kjsmita6** [comment]
Just logging in with parentbot will activate it automatically assuming it isn't activated anywhere else.

**Comment by CodeLuca** [comment]
I dont seem to have these files inside my project directory when running my bot.

**Comment by CodeLuca** [comment]
My end goal here is to get automatic trade confirmations when I send a trade.

**Comment by CodeLuca** [comment]
@andrewda @dragonbanshee @infam0us

**Comment by mert574** [comment]
Apparently, your 2FA is activated somewhere else. If you don't know where you activated it, no one can help.

**Comment by CodeLuca** [comment]
this is all of the stuff I do in my index.js file, which activates parentbot: https://gist.github.com/CodeLuca/44de80dfc35619357b26
@infam0us

**Comment by mert574** [comment]
@CodeLuca your 2FA problem is not about the code. It's about your steam account.
THIS IS "2FA":
https://support.steampowered.com/kb_article.php?ref=4440-RTUI-9218&l=english
https://github.com/Jessecar96/SteamDesktopAuthenticator/

https://steamcommunity.com/groups/MobileAuthBeta/discussions/0/530646080841787169/

**Comment by CodeLuca** [comment]
I can receive trades with the code I have written just auto confirming them that is the problem. You sure this is to do with the account?

Tuesday, 22 March 2016, 10:43 +0000 from notifications@github.com  notifications@github.com:

**Comment by CodeLuca** [comment]
@infam0us I know what 2FA is, I have enabled it and I have used it in other parts of the same project, I just need the identity secret to auto accept trades.

**Comment by CodeLuca** [comment]
#17
