### ISSUE TITLE
Why steam is not working

### ISSUE THREAD

**Issue by Xeroner** [dragonbanshee/node-steam-parentbot#16]
Why is not working ?

`var ParentBot = require('steam-parentbot'); //change to 'steam-parentbot' if not running from examples directory
var Steam = ParentBot.Steam; //instance of the Steam object`

`Steam.webLogOn(function(newCookie) {
                        Bot.offers.setup({
                            sessionID: globalSessionID,
                            webCookie: newCookie
                        }, function(err) {
                            if (err) {
                            }
                        });
                    });`

`TypeError: Steam.webLogOn is not a function`

**Comment by kjsmita6** [comment]
Well as the error says, `Steam.webLogOn` doesn't exist. Also there's no reason to call weblogon since it is automatically called when you log in with default parentbot config.

**Comment by Xeroner** [comment]
True, it's not needed :+1:  :) Closed.
