### ISSUE TITLE
How to get .2fa_info files.

### ISSUE THREAD

**Issue by CodeLuca** [dragonbanshee/node-steam-parentbot#17]
I need to get the identity secret to auto accept trades which is apparently located in the [username].2fa_info file. For some reason I don't have this file. I have already enabled 2fa, and have written working code for auto accepting trade offers. At the moment only sentry and log files are created not the .2fa_info files which I need in order to find the identity secret.

This is the code of my index file where I create the childbot: https://gist.github.com/CodeLuca/44de80dfc35619357b26

I am using the mobile authenticator on iOS if that helps.
This issue is an extension of #15 

If @andrewda, @dragonbanshee or @infam0us could you try help me out? Thanks so much for the help already :)

Thanks,
Luca

**Comment by CodeLuca** [comment]
@dragonbanshee

**Comment by CodeLuca** [comment]
@andrewda, @dragonbanshee or @infam0us Emergency help needed!

**Comment by kjsmita6** [comment]
You need to have enabled 2FA on parentbot, which means it can't be enabled anywhere else. If it is, disable it. Then when you run parentbot after, it will walk you through the process to enable 2FA on the bot. Once it's enabled, the file will be automatically generated and you will have the information.

**Comment by CodeLuca** [comment]
@dragonbanshee where else could it be enabled. And by somewhere else, do you mean elsewhere in the code or in other programs / processes?
