### ISSUE TITLE
Cannot Automatically Accept Trade Offers

### ISSUE THREAD

**Issue by CodeLuca** [dragonbanshee/node-steam-parentbot#18]
@andrewda,
I need some help, I cannot seem to get the auto confirming of trade offers working, here is my code when activating the bot with a couple numbers changed from the identity_secret:

```
// Initialise App.ChildBot
App.Bot = new App.ChildBot(App.config.username, App.config.password, {
  apikey: App.config.apiKey,
  twoFactorCode: App.config.twoFactorCode,
  identitySecret: 'u8OxVY+GJ32IlX9mlmcrkW/d4B4=',
  confirmationInterval: 10000
});
debug('Childbot Initialised');
```

**Comment by andrewda** [comment]
Well the code you supplied certainly won't accept trades automatically, you're just initializing the child bot. I can try to whip you up something really basic in a couple minutes that you can then work off of. Basically, you'll need to initialize a tradeoffers instance and listen for the new offer event.

**Comment by CodeLuca** [comment]
@andrewda no need, I already have that code ready. What do I need inside the event to activate accepting?

**Comment by andrewda** [comment]
Checkout the `acceptOffer()` method.

https://github.com/Alex7Kom/node-steam-tradeoffers#acceptofferoptions-callback

**Comment by CodeLuca** [comment]
`acceptOffer that was sent to you.` I'm sending the offer not receiving it. @andrewda

**Comment by andrewda** [comment]
> What do I need inside the event to activate accepting?

What are you trying to accept, then?

**Comment by CodeLuca** [comment]
@andrewda  fack I've completely titled this question wrong -.- not slept enough

**Comment by CodeLuca** [comment]
@andrewda I'm trying to automatically confirm trade offers that im sending.

**Comment by CodeLuca** [comment]
@andrewda updated the message in the original question.

**Comment by andrewda** [comment]
Ahh, I see now. You'll need to use a `steamCommunity` instance and use [`startConfirmationChecker(pollInterval[, identitySecret])`](https://github.com/DoctorMcKay/node-steamcommunity/wiki/Steam-Confirmation-Polling#startconfirmationcheckerpollinterval-identitysecret). That will check to see if there are any new confirmations and, if there are, confirm them. Note that you'll also have to [`setCookies(cookies)`](https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#setcookiescookies).

**Comment by CodeLuca** [comment]
@andrewda any chance you can whip up an example of how to setup Cookies and in what context this should be done?

**Comment by CodeLuca** [comment]
@andrewda why does setCookies(cookies) have to be used?

**Comment by andrewda** [comment]
setCookies() is needed to "login" to steamCommunity, which is a separate module from the one you're logging in with.

**Comment by CodeLuca** [comment]
@andrewda how do I parse the login information into that then?

**Comment by CodeLuca** [comment]
@andrewda https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#setcookiescookies doesn't seem to give too much info about what I need to parse? I'm just a little confused sorry! Thanks for the help :+1:

**Comment by andrewda** [comment]
Using a [`steamWeblogon`](https://github.com/Alex7Kom/node-steam-weblogon) instance. It just needs to be an array of cookies.

**Comment by CodeLuca** [comment]
@andrewda is there an instance created when creating an instance of parentbot or do I need to create a separate instance?

**Comment by andrewda** [comment]
If I'm not mistaken, you'll have to make a new instance of every module you plan to use in your app.

The `setCookies()` method should be used once you're completely logged into Steam.

**Comment by CodeLuca** [comment]
@andrewda I thought that a steamWeblogin is created through steam-parentbot: `steamWebLogon - an instance of SteamWebLogon (use this for logging into Steam web, replacement for steamClient.on('webSessionID');`

**Comment by CodeLuca** [comment]
@andrewda so surely you can do something like: `setCookies(bot.steamWebLogon)`

**Comment by andrewda** [comment]
``` js
//your login stuff here

Bot.steamClient.on('logOnResponse', function(logonResp) {
    Bot.steamWebLogon.webLogOn(function(webSessionID, cookies) {
        Bot.steamCommunity.setCookies(cookies);
        Bot.steamCommunity.startConfirmationChecker(10000, identity_secret);
    });
});
```

that should be all you need to get started

**Comment by kjsmita6** [comment]
@andrewda you already added the confirmation checker in [this pr](https://github.com/dragonbanshee/node-steam-parentbot/pull/3), I think he's saying it doesn't work? I think my bots have also been having problems with this, but I'm not sure.

I have no idea how to do any of this stuff so I can't help much.

**Comment by andrewda** [comment]
I completely forgot about that, @dragonbanshee! I'll try and debug this issue now, @CodeLuca, sorry about that.

**Comment by andrewda** [comment]
@dragonbanshee @CodeLuca #19 fixed the problem for me in my tests!

**Comment by kjsmita6** [comment]
Ok it's on npm as version 2.2.5.

**Comment by CodeLuca** [comment]
@andrewda will the code that you wrote earlier in this issue work then?

**Comment by CodeLuca** [comment]
@andrewda @dragonbanshee still not working for me even with newest version of the module... I'm getting this warning if it helps anyone? `warn: [tripleskinsbot] Already have 2FA enabled`

**Comment by CodeLuca** [comment]
@andrewda @dragonbanshee also started the confirmation checker manually, and still nothing :/

**Comment by CodeLuca** [comment]
Got it to work! Thanks for the help everyone!
