### ISSUE TITLE
Offer sending failure

### ISSUE THREAD

**Issue by Xeroner** [dragonbanshee/node-steam-parentbot#20]
Hi there, what is 15 code on my error?

There was an error sending your trade offer.  Please try again later. (15)

**Comment by andrewda** [comment]
http://steamerrors.com/15

> Either you are sending a trade offer without being friends with the recipient (and without providing a valid trade offer access token), or the inventory of one of the parties in this trade is full. This can also happen if the other party is trade banned in that specific game (e.g. a VAC ban in CS:GO).

**Comment by Xeroner** [comment]
Thanks for info :)
Other error witch i'm getting from time to time is :

> Error: number format error: empty string
>     at Error (native)
>     at Function.fromString (/var/www/csboxpl2/app/node_modules/steam-tradeoffers/node_modules/long/dist/Long.js:204:19)
>     at toAccountId (/var/www/csboxpl2/app/node_modules/steam-tradeoffers/index.js:362:15)
>     at SteamTradeOffers.makeOffer (/var/www/csboxpl2/app/node_modules/steam-tradeoffers/index.js:260:42)
>     at null._onTimeout (/var/www/csboxpl2/app/socket.js:753:40)
>     at Timer.listOnTimeout (timers.js:92:15)

**Comment by kjsmita6** [comment]
It says the error is on line 753 of your file socket.js. Could you post that line?

**Comment by Xeroner** [comment]
It's resolved now,

> It clearly means that from time to time you pass an empty string as partnerSteamId.
