### ISSUE TITLE
I'm getting unexpected disconnection all the time

### ISSUE THREAD

**Issue by CodeLuca** [dragonbanshee/node-steam-parentbot#22]
Hey,
I have no idea why, but my bot is getting disconnected all the time and as the account is using separate mobile authentication, not embedded into steam-parent-bot, I cannot make it automatically restart.
help?

**Comment by CodeLuca** [comment]
This especially happens after accepting / declining trade requests.

**Comment by andrewda** [comment]
Well, Steam will be Steam and will disconnect you from time to time, especially during high-load on the Steam servers. I think your main problem is using an external mobile authenticator. Why not use the one parent-bot already has?

**Comment by CodeLuca** [comment]
@andrewda I'm planning on releasing my site tomorrow and I cant afford the 7 day cooldown of trading.

**Comment by CodeLuca** [comment]
@andrewda is there anything I can do? :/

**Comment by andrewda** [comment]
You certainly can't automatically reconnect if you have to manually type in your authcode, and, again, Steam is hard to predict. Your choices are really to either accept the cool down or to risk being disconnected every so often.

**Comment by CodeLuca** [comment]
I'm going to make a new bot account with server enabled mobile Auth but risk it with the current one. 

Friday, 1 April 2016, 22:20 +0100 from notifications@github.com  notifications@github.com:
