### ISSUE TITLE
Handling Offers

### ISSUE THREAD

**Issue by yoranjj** [dragonbanshee/node-steam-parentbot#26]
Hi,

If two or more trades were sent to the bot within 1-2 seconds of eachother it would handle both of them twice, duplicating them basically. Is there a way of not letting this happen? A queue perhaps? If so, how would I go on about doing so?

Yoran.

**Comment by kjsmita6** [comment]
If you have 2 offers at the same time it will be two separate offer objects, meaning that Bot.offers.getOffers() will return 2 things. If you handle them with a foreach statement then it shouldn't duplicate it.

``` javascript
Bot.offers.getOffers(... function(offers) {
    offers.forEach(function(offer) {
        handleOffer(offer);
    });
});
```

**Comment by kjsmita6** [comment]
Closed due to inactivity.
