### ISSUE TITLE
[Q] Worth changing to ES6 version?

### ISSUE THREAD

**Issue by mert574** [dragonbanshee/node-steam-parentbot#29]
Question is clear: I have a stable working bot. Should I upgrade to ES6 version of parentbot?

**Comment by kjsmita6** [comment]
Doesn't matter, they both have the same functionality. I mainly made the ES6 one to  teach myself the new syntax and show the differences between mainly ES5 and full ES6. Some of the old bot uses ES6 (arrow functions, `const`, etc).
