### ISSUE TITLE
steamCommunity instance is 'community'?

### ISSUE THREAD

**Issue by ghost** [dragonbanshee/node-steam-parentbot#30]
Hello there, I tried kicking members from the group using the steamCommunity instance, but everytime I use 'Bot.steamCommunity' it fails, and when I use(viewed the source) 'Bot.community' it only gives the error I wouldn't have permissions, even though I can kick manually..

```
Bot.steamCommunity.kickGroupMember('', new SteamID('[U:1:]'), function (err) {
            console.log(err);
        });

Bot.community.kickGroupMember('', new SteamID('[U:1:]'), function (err) {
            console.log(err);
        });
```

Error:

```
Bot.steamCommunity.kickGroupMember('', new SteamID('[U:1:]'), function (err) {
                                  ^

TypeError: Cannot read property 'kickGroupMember' of undefined


-----


Error: You do not have the required permissions to access that group feature.
    at SteamCommunity._checkCommunityError (/home/bots/node_modules/steam-parentbot/node_modules/steamcommunity/components/http.js:110:9)
    at Request._callback (/home/bots/node_modules/steam-parentbot/node_modules/steamcommunity/components/http.js:51:88)
    at Request.self.callback (/home/bots/node_modules/steam-parentbot/node_modules/steamcommunity/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/bots/node_modules/steam-parentbot/node_modules/steamcommunity/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (/home/bots/node_modules/steam-parentbot/node_modules/steamcommunity/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
```

**Comment by kjsmita6** [comment]
You need to use '`Bot.community.kickGroupMember`. Usage is this:

``` javascript
Bot.community.kickGroupMember(new SteamID('group id'), new SteamID('user id'), function(err) {
    console.log(err.stack);
});
```

I'm not sure if the first argument needs to be a `SteamID` object. Try this and see if it works. If not, your best bet would be to create an instance of `CSteamGroup` and use the `Bot.community.kick` method.

**Comment by ghost** [comment]
As you can see above, I did it also with SteamID object, the group doesnt need to be one, as the example says in the wiki. The code itself works, but it says I got no permission? But when I access the account manually, i can groupkick.

**Comment by ghost** [comment]
overall the whole .community doesn't seem to work, cant even join/leave groups.

**Comment by kjsmita6** [comment]
Are you using the default `_onLogOnResponse` or did uiu make your own?

**Comment by ghost** [comment]
I overwrote _onLogOnResponse and _onFriendMessage.

**Comment by kjsmita6** [comment]
Ok, I'm gonna assume then that you didn't set the steamcommunity cookies, which you need. Check the parentbot.js file on how to do that.

**Comment by ghost** [comment]
So this should work..?

```
this.steamWebLogon.webLogOn(function (webSessionID, cookies) {
            Bot.community.setCookies(cookies);
        });
```

sorry I'm new to the whole 'new'-ish stuff, I used the old plain simple node-steam back before all the updates.

**Comment by kjsmita6** [comment]
Yeah, make sure you put it in the _onLogOnResponse and then you should be able to kick people.

Basically without the cookies, steam-community doesn't know who you are so you aren't able to do anything.

**Comment by ghost** [comment]
Alrighty it works, thanks for the support! :heart:
