### ISSUE TITLE
Limit numbers of cSteamGroup.getGroupMembers() returns

### ISSUE THREAD

**Issue by ghost** [dragonbanshee/node-steam-parentbot#31]
Ehhh hello, I just simply wanted to ask, if you know a method to limit the returns of the given function, wich crawls groups to get their members? Since I once crawled a big group, and it kept going on forever, until nodeJS crashed, I want to grab only the first 100 members, if possible, and then stop the crawling, and go on with the code.

**Comment by kjsmita6** [comment]
Looking at the [documentation](https://github.com/DoctorMcKay/node-steamcommunity/wiki/CSteamGroup#getmembersaddresses-callback)
it doesn't look like you are able to limit the amount of members. It looks
like the method gets all the members of the group.

**Comment by originalwhitestar** [comment]
well hmm.. could you tell me, why always cSteamUser.groups is 'undefined'? I always check if the profile is public, and if it is, then it shall check if the groups array contains a specific ID(and if I print the array, it always is undefined, making my bot crash eventually)?

**Comment by originalwhitestar** [comment]
Alright I got that fixed somehow, but I didnt see anywhere in steamCommunity, steamUser, steamClient & steamFriends to somehow retrieve if a user is a specific rank(eg mod) in the group, just in the chat.

**Comment by ghost** [comment]
Alright I got that now fixed, but is it somehow possible to like, make the bot check for comments on its profile, like as example /addme, or /invite? Because I see nowhere anything, and CSteamConfirmation is only for trades, and if not, I cannot see a method to read what string the comment is.

**Comment by kjsmita6** [comment]
I don't think so. The only way would be to manually get the comment from the html.

**Comment by ghost** [comment]
Ahhh crap, Most websites 'block' XMLHTTPRequest crawling, like google etc, I've to see, maybe I use node-request and try that, either way, thanks for the help!
