### ISSUE TITLE
Socked

### ISSUE THREAD

**Issue by emdy** [dragonbanshee/node-steam-parentbot#6]
How to currectly do this?
![1111](https://cloud.githubusercontent.com/assets/16139265/11784392/1067e0f4-a28d-11e5-9c22-2f8ff78f5a0d.png)

**Comment by kjsmita6** [comment]
That's an error with escrow. I am going to write some stuff to enable it.

**Comment by kjsmita6** [comment]
Added in https://github.com/dragonbanshee/node-steam-parentbot/commit/5cdce8937819bf5e16b6ffd31c8c0dbb18cdd232

**Comment by emdy** [comment]
@dragonbanshee I get this error again and again :(

**Comment by kjsmita6** [comment]
Update to the newest version,  and it should automatically enable two factor for you. Once it does, take the shared_secret and identitiy_secret from the file and add to your config file. It looks like you already have it enabled though,  so you need to disable it first.

**Comment by emdy** [comment]
@dragonbanshee where are this cfg and where i can disable this? I need to register phone nr somewhere in modules?
